// <auto-generated />
using System;
using Imperium_Incursions_Waitlist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Imperium_Incursions_Waitlist.Migrations
{
    [DbContext(typeof(WaitlistDataContext))]
    [Migration("20190503113712_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Account", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("LastLogin");

                    b.Property<string>("LastLoginIP");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("RegisteredAt");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.AccountRole", b =>
                {
                    b.Property<int>("AccountId");

                    b.Property<int>("RoleId");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Alliance", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Alliance");
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int>("BannedAccountId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("ExpiresAt");

                    b.Property<string>("Reason");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UpdatedByAdminId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("BannedAccountId");

                    b.HasIndex("UpdatedByAdminId");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Corporation", b =>
                {
                    b.Property<long>("Id");

                    b.Property<int?>("AllianceId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId")
                        .IsUnique()
                        .HasFilter("[AllianceId] IS NOT NULL");

                    b.ToTable("Corporation");
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Pilot", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("AccountId");

                    b.Property<long>("CorporationId");

                    b.Property<string>("ESIToken");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("RegisteredAt");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CorporationId");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Commander"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Leadership"
                        });
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.AccountRole", b =>
                {
                    b.HasOne("Imperium_Incursions_Waitlist.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Imperium_Incursions_Waitlist.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Ban", b =>
                {
                    b.HasOne("Imperium_Incursions_Waitlist.Models.Account", "CreatorAdmin")
                        .WithMany("CreatedBans")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imperium_Incursions_Waitlist.Models.Account", "BannedAccount")
                        .WithMany("AccountBans")
                        .HasForeignKey("BannedAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Imperium_Incursions_Waitlist.Models.Account", "UpdatingAdmin")
                        .WithMany("UpdatedBans")
                        .HasForeignKey("UpdatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Corporation", b =>
                {
                    b.HasOne("Imperium_Incursions_Waitlist.Models.Alliance", "Alliance")
                        .WithOne("Corporation")
                        .HasForeignKey("Imperium_Incursions_Waitlist.Models.Corporation", "AllianceId");
                });

            modelBuilder.Entity("Imperium_Incursions_Waitlist.Models.Pilot", b =>
                {
                    b.HasOne("Imperium_Incursions_Waitlist.Models.Account", "Account")
                        .WithMany("Pilots")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Imperium_Incursions_Waitlist.Models.Corporation", "Corporation")
                        .WithMany("Pilots")
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
